name: "Continous Integration"

on:
  push:
    branches: 
      - "*/**"

jobs:
  test:
    name: Check all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

     - name: Use latest version of Node
       uses: actions/setup-node@v4
       with:
         node-version: "20"
         cache: pnpm
    
    - name: Install dependencies
      run: pnpm install

    - name: Run check all
      env:
        CI: true
      run: pnpm check:all