name: Continous Integration

on:
  push:
    branches: 
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    name: Check all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Bun
        uses: oven-sh/setup-bun@v2

      - name: Setup node version
        uses: actions/setup-node@v6
        with:
          node-version: "24"
    
      - name: Install dependencies
        run: bun install

      - name: Run build
        run: bun run build

      - name: Run check all
        env:
          CI: true
        run: bun run check:all